# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20180423_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
