# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20180423_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
