# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20180423_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Post',
        ),
    ]
