# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDef', models.CharField(max_length=150)),
                ('wordEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_display.word')),
            ],
        ),
    ]
