# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_display', '0002_users_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_def',
            name='def_votes',
            field=models.IntegerField(default=0),
        ),
    ]
